name: tests

on:
  push:
    branches: [main]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Nix
        uses: cachix/install-nix-action@v27

      - name: Install devenv
        run: nix profile install github:cachix/devenv

      - name: Run tests
        run: devenv test --no-tui
